name: traffeye_sg_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  drag_and_drop_lists: ^0.3.3
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_spinkit: ^5.2.0
  geocoding: ^2.1.0
  get: ^4.6.5
  google_fonts: ^5.1.0
  hive: ^2.2.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/filled/
    - assets/vectors/images/
    - assets/vectors/outlined/