import 'package:traffeye_sg_flutter/2_application/core/helpers/intl_helper.dart';

abstract class IntlEnUs {
  static final translations = {
    IntlHelper.cancel: 'Cancel',
    IntlHelper.cardCamerasTitle: 'Explore Cameras',
    IntlHelper.cardCamerasSubtitle: 'Map view for available cameras',
    IntlHelper.cardWidgetsTitle: 'Home Widgets',
    IntlHelper.cardWidgetsSubtitle: 'Get updates from your home screen',
    IntlHelper.carousel: 'Carousel',
    IntlHelper.close: 'Close',
    IntlHelper.customName: 'Custom Name',
    IntlHelper.customNameHint: 'E.g., My Apartment',
    IntlHelper.errorNoActivatedSectionsTitle: 'No Activated Sections',
    IntlHelper.errorNoActivatedSectionsSubtitle: 'Configure this in the *Dashboard* settings',
    IntlHelper.errorNoSavedCamerasTitle: 'No Saved Cameras',
    IntlHelper.errorNoSavedCamerasSubtitle: 'Add a saved camera through *Explore Cameras*',
    IntlHelper.errorNoCamerasFoundTitle: 'No Cameras Found',
    IntlHelper.errorNoCamerasFoundSubtitle: 'Try using a different keyword',
    IntlHelper.features: 'Features',
    IntlHelper.grid: 'Grid',
    IntlHelper.list: 'List',
    IntlHelper.save: 'Save',
    IntlHelper.savedCameras: 'Saved Cameras',
    IntlHelper.searchCameraHint: 'Search among @count cameras',
    IntlHelper.splashCaption: 'Singapore Traffic Camera Snapshots',

    // * Last Updated
    IntlHelper.lastUpdated: 'Last updated',
    IntlHelper.daysAgo: 'days ago',
    IntlHelper.hoursAgo: 'hours ago',
    IntlHelper.justNow: 'just now',
    IntlHelper.minutesAgo: 'minutes ago',
    IntlHelper.aLongTimeAgo: 'a long time ago',

    // * Profile
    IntlHelper.profile: 'Profile',
    IntlHelper.about: 'About',
    IntlHelper.aboutTitle: 'Description',
    IntlHelper.aboutTexts: "*TraffEye SG* is a 100% free, no ads, and open-source Flutter Android and iOS app made to get live snapshots of traffic cameras in Singapore.\nI will attribute the technologies and assets used to develop this app below. I will also put in the app's repository and Figma file for this app.",
    IntlHelper.aboutFlutter: 'Flutter',
    IntlHelper.aboutIconsax: 'Iconsax',
    IntlHelper.aboutUnsplash: 'Unsplash',
    IntlHelper.aboutCameraApi: "Traffic Camera's API",
    IntlHelper.aboutFigma: "TraffEye's Figma",
    IntlHelper.aboutGitHub: "TraffEye's GitHub",
    IntlHelper.dashboard: 'Dashboard',
    IntlHelper.dashboardLayout: 'Dashboard Layout',
    IntlHelper.dashboardLayoutTitle: 'Definition',
    IntlHelper.dashboardLayoutTexts: 'Dashboard layout will change the layout of your *Saved Cameras* section in your dashboard page.',
    IntlHelper.dashboardLayoutButton: 'Change Layout',
    IntlHelper.donate: 'Donate',
    IntlHelper.donateTitle: 'Reasons to Donate',
    IntlHelper.donateTexts: 'Well, there are no obligations for you to donate.\nI specifically made this app as a passion project that will help you as a user while also helping fellow developers because of the open-source nature of this app.\nBut obviously, I will not reject a cup of coffee or a slice of pizza from you!',
    IntlHelper.donateButton: 'Donate through Ko-fi',
    IntlHelper.homeWidgetsTitle: 'Adding Widgets Steps',
    IntlHelper.homeWidgetsTexts: "To add a widget to view your saved cameras from your phone’s home screen, do these steps:\nGo to the home screen by pressing the home button\nTap and hold at an empty space on the home screen\nTap *Widgets* and find a widget from *TraffEye SG*\nThese steps may vary for some devices.",
    IntlHelper.location: 'Location',
    IntlHelper.locationTitle: 'Uses of Location',
    IntlHelper.locationTexts: 'The selected location will only used for getting the optional weather updates. You can turn off the *Weather* section in the previous page if you don’t need it.',
    IntlHelper.other: 'Other',
    IntlHelper.personalization: 'Personalization',
  };
}